const { contextBridge, ipcRenderer } = require('electron')

const invoke = (channel, payload) => ipcRenderer.invoke(channel, payload)

contextBridge.exposeInMainWorld('growthArc', {
  dashboard: () => invoke('dashboard:get'),
  world: {
    get: () => invoke('world:get'),
    updatePlayer: (data) => invoke('player:update', data),
  },
  structure: {
    get: () => invoke('structure:get'),
    getAll: () => invoke('structure:get-all'),
    createArea: (data) => invoke('area:create', data),
    updateArea: (id, data) => invoke('area:update', { id, data }),
    archiveArea: (id) => invoke('area:archive', id),
    restoreArea: (id) => invoke('area:restore', id),
    deleteArea: (id) => invoke('area:delete', id),
    createGoal: (data) => invoke('goal:create', data),
    updateGoal: (id, data) => invoke('goal:update', { id, data }),
    deleteGoal: (id) => invoke('goal:delete', id),
    archiveGoal: (id) => invoke('goal:archive', id),
    restoreGoal: (id) => invoke('goal:restore', id),
    createTask: (data) => invoke('task:create', data),
    updateTask: (id, patch) => invoke('task:update', { id, patch }),
    reorderTasks: (items) => invoke('task:reorder', items),
    deleteTask: (id) => invoke('task:delete', id),
    restoreTask: (id) => invoke('task:restore', id),
    reopenTask: (id) => invoke('task:reopen', id),
    manualComplete: (id) => invoke('task:manual-complete', id),
  },
  session: {
    active: () => invoke('session:active'),
    start: (data) => invoke('session:start', data),
    heartbeat: (id) => invoke('session:heartbeat', id),
    pause: (id) => invoke('session:pause', id),
    resume: (id) => invoke('session:resume', id),
    stop: (id, data) => invoke('session:stop', { id, data }),
    cancel: (id) => invoke('session:cancel', id),
  },
  companions: {
    get: () => invoke('companions:get'),
    setActive: (id) => invoke('companions:set-active', id),
    rename: (id, nickname) => invoke('companions:rename', { id, nickname }),
    getPendingGrowth: () => invoke('companions:get-pending-growth'),
    markGrowthSeen: (id) => invoke('companions:mark-growth-seen', id),
    evolve: (id, pathId) => invoke('companions:evolve', { id, pathId }),
  },
  history: (limit) => invoke('history:get', limit),
  review: {
    daily: (date) => invoke('review:daily', date),
    saveDaily: (data) => invoke('review:save-daily', data),
    weekly: (date) => invoke('review:weekly', date),
  },
  settings: {
    get: () => invoke('settings:get'),
    set: (data) => invoke('settings:set', data),
    hasApiKey: () => invoke('settings:has-api-key'),
    setApiKey: (key) => invoke('settings:set-api-key', key),
    clearApiKey: () => invoke('settings:clear-api-key'),
    openDataFolder: () => invoke('settings:open-data-folder'),
    getBgmSources: () => invoke('settings:get-bgm-sources'),
    openBgmFolder: () => invoke('settings:open-bgm-folder'),
    getBirthday: () => invoke('settings:get-birthday'),
    setBirthday: (month, day) => invoke('settings:set-birthday', { month, day }),
  },
  ai: {
    generate: (type, date) => invoke('ai:generate', { type, date }),
  },
  inventory: {
    use: (itemId) => invoke('inventory:use', itemId),
    useTarget: (itemId, companionId, targetStage = null) => invoke('inventory:use-target', { itemId, companionId, targetStage }),
  },
  hearth: {
    get: () => invoke('hearth:get'),
    setLit: (lit) => invoke('hearth:set-lit', lit),
    craft: (recipeId) => invoke('hearth:craft', recipeId),
  },
  caravan: {
    buy: (sessionId, slotIndex) => invoke('caravan:buy', { sessionId, slotIndex }),
  },
  bard: { claim: (sessionId) => invoke('bard:claim', sessionId), list: () => invoke('bard:list') },
  memos: {
    get: () => invoke('memos:get'),
    create: (data) => invoke('memos:create', data),
    update: (id, patch) => invoke('memos:update', { id, patch }),
    trash: (id) => invoke('memos:trash', id),
    restore: (id) => invoke('memos:restore', id),
    deletePermanently: (id) => invoke('memos:delete-permanently', id),
    createFolder: (name) => invoke('memo-folders:create', name),
    updateFolder: (id, name) => invoke('memo-folders:update', { id, name }),
    deleteFolder: (id) => invoke('memo-folders:delete', id),
  },
  observatory: {
    getDaily: (dateOrTimestamp) => invoke('observatory:get-daily', dateOrTimestamp),
    getWeekly: (dateOrTimestamp) => invoke('observatory:get-weekly', dateOrTimestamp),
    getMonthly: (dateOrTimestamp) => invoke('observatory:get-monthly', dateOrTimestamp),
    getYearly: (dateOrTimestamp) => invoke('observatory:get-yearly', dateOrTimestamp),
    listManual: (start, end) => invoke('observatory:list-manual', { start, end }),
    createManual: (data) => invoke('observatory:create-manual', data),
    deleteManual: (id) => invoke('observatory:delete-manual', id),
    getReview: (date) => invoke('observatory:get-review', date),
    saveReview: (data) => invoke('observatory:save-review', data),
  },
  mail: {
    list: (opts) => invoke('mail:list', opts),
    get: (id) => invoke('mail:get', id),
    getUnreadCount: () => invoke('mail:get-unread-count'),
    getLatestUnread: () => invoke('mail:get-latest-unread'),
    markRead: (id) => invoke('mail:mark-read', id),
    markUnread: (id) => invoke('mail:mark-unread', id),
    saveReply: (id, replyText) => invoke('mail:save-reply', { id, replyText }),
    ensurePeriodic: (simTs) => invoke('mail:ensure-periodic', simTs),
    testLetter: () => invoke('mail:test-letter'),
  },
  dev: {
    cleanTestEvents: () => invoke('dev:clean-test-events'),
    dbInfo: () => invoke('dev:db-info'),
    resetMailTimeline: () => invoke('dev:reset-mail-timeline'),
    diagnoseMail: () => invoke('dev:diagnose-mail'),
  },
  window: {
    show: () => ipcRenderer.send('window:show'),
  },
    focusWidget: {
      getState: () => invoke('focus-widget:get-state'),
      showMain: () => ipcRenderer.send('focus-widget:show-main'),
      hide: () => ipcRenderer.send('focus-widget:hide'),
    onState: (listener) => {
      const handler = (_event, state) => listener(state)
      ipcRenderer.on('focus-widget:state', handler)
      return () => ipcRenderer.removeListener('focus-widget:state', handler)
    },
  },
})
