const WORLD_CONTENT_NAMESPACE = 'core-world'
const WORLD_CONTENT_VERSION = '0.1.0'

const WORLD_REGIONS = [
  {
    id: 'border_town',
    name: '边境城镇',
    layer: 1,
    description: '主角选择安顿下来的温暖边境城镇，也是每次远征的返程之地。',
    sortOrder: 10,
    initialState: 'discovered',
  },
  {
    id: 'pinewind_forest',
    name: '松风林',
    layer: 2,
    description: '城镇附近的松林与旧路，第一次正式远征从这里开始。',
    sortOrder: 20,
    initialState: 'rumored',
  },
  {
    id: 'white_stone_valley',
    name: '白石河谷',
    layer: 2,
    description: '河流、牧场、水磨坊与旧石桥组成的商队通路。',
    sortOrder: 30,
    initialState: 'rumored',
  },
  {
    id: 'old_watch_hills',
    name: '旧望丘陵',
    layer: 2,
    description: '散布着旧哨塔、采石场和烽火台的石质丘陵。',
    sortOrder: 40,
    initialState: 'rumored',
  },
]

const WORLD_NODES = [
  {
    id: 'cottage',
    regionId: 'border_town',
    kind: 'home',
    name: '边境小屋',
    description: '主角、小狗与未来家人共同生活的私人住所。',
    mapX: 18,
    mapY: 62,
    sortOrder: 10,
    initialState: 'discovered',
  },
  {
    id: 'town_square',
    regionId: 'border_town',
    kind: 'settlement',
    name: '城镇广场',
    description: '连接旅店、公会、制图桌和城门的城镇中心。',
    mapX: 36,
    mapY: 52,
    sortOrder: 20,
    initialState: 'discovered',
  },
  {
    id: 'cartography_room',
    regionId: 'border_town',
    kind: 'building',
    name: '制图桌',
    description: '莉娅整理旧地图和未确认道路的工作地点。',
    mapX: 44,
    mapY: 43,
    sortOrder: 30,
    initialState: 'discovered',
  },
  {
    id: 'pinewind_gate',
    regionId: 'pinewind_forest',
    kind: 'trailhead',
    name: '松风林入口',
    description: '从城镇北门通向松风林的旧路起点。',
    mapX: 52,
    mapY: 34,
    sortOrder: 40,
    initialState: 'rumored',
  },
  {
    id: 'fallen_signpost',
    regionId: 'pinewind_forest',
    kind: 'landmark',
    name: '倒下的路牌',
    description: '多年无人确认的旧路标，也是第一次远征的目的地。',
    mapX: 66,
    mapY: 24,
    sortOrder: 50,
    initialState: 'hidden',
  },
  {
    id: 'pinewind_fork',
    regionId: 'pinewind_forest',
    kind: 'junction',
    name: '林间岔路',
    description: '路牌后方仍未探索的岔路，通往松风林深处。',
    mapX: 78,
    mapY: 18,
    sortOrder: 60,
    initialState: 'hidden',
  },
  {
    id: 'white_stone_bridge',
    regionId: 'white_stone_valley',
    kind: 'landmark',
    name: '白石旧桥',
    description: '商队进入边境城镇前必须经过的古老石桥。',
    mapX: 74,
    mapY: 58,
    sortOrder: 70,
    initialState: 'rumored',
  },
  {
    id: 'old_watchtower',
    regionId: 'old_watch_hills',
    kind: 'landmark',
    name: '旧望哨塔',
    description: '能够眺望群山与远方龙影的废弃哨塔。',
    mapX: 28,
    mapY: 16,
    sortOrder: 80,
    initialState: 'rumored',
  },
]

const WORLD_EDGES = [
  {
    id: 'cottage_to_square',
    fromNodeId: 'cottage',
    toNodeId: 'town_square',
    distance: 1,
    initialState: 'discovered',
  },
  {
    id: 'square_to_cartography',
    fromNodeId: 'town_square',
    toNodeId: 'cartography_room',
    distance: 1,
    initialState: 'discovered',
  },
  {
    id: 'square_to_pinewind',
    fromNodeId: 'town_square',
    toNodeId: 'pinewind_gate',
    distance: 2,
    initialState: 'rumored',
  },
  {
    id: 'pinewind_to_signpost',
    fromNodeId: 'pinewind_gate',
    toNodeId: 'fallen_signpost',
    distance: 3,
    initialState: 'hidden',
  },
  {
    id: 'signpost_to_fork',
    fromNodeId: 'fallen_signpost',
    toNodeId: 'pinewind_fork',
    distance: 2,
    initialState: 'hidden',
  },
]

module.exports = {
  WORLD_CONTENT_NAMESPACE,
  WORLD_CONTENT_VERSION,
  WORLD_REGIONS,
  WORLD_NODES,
  WORLD_EDGES,
}
